# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Addlicense < Formula
  desc "Fast, minimal license header manager for monorepos and CI pipelines."
  homepage "https://github.com/GregoireF/addlicense"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GregoireF/addlicense/releases/download/v0.2.0/addlicense_darwin_amd64.tar.gz"
      sha256 "d0b01edafe0ea5c4f82df69e79635e407a90cd419323783cb335df0b24b00008"

      define_method(:install) do
        bin.install "addlicense"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GregoireF/addlicense/releases/download/v0.2.0/addlicense_darwin_arm64.tar.gz"
      sha256 "b4f336184a524a5364403a5150a6f7eb2345cacc28766ea591887dd58abdae6b"

      define_method(:install) do
        bin.install "addlicense"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GregoireF/addlicense/releases/download/v0.2.0/addlicense_linux_amd64.tar.gz"
      sha256 "e468218f69b984f478f7f2775d3f830e8d14233479c654a15f6b4d34fb14e949"
      define_method(:install) do
        bin.install "addlicense"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GregoireF/addlicense/releases/download/v0.2.0/addlicense_linux_arm64.tar.gz"
      sha256 "d88daaed1cd21f94451574aa16402aa1b370b7987e3ee4d3f14f77f573169bbe"
      define_method(:install) do
        bin.install "addlicense"
      end
    end
  end

  test do
    system "#{bin}/addlicense", "--version"
  end
end
