# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Addlicense < Formula
  desc "Fast, minimal license header manager for monorepos and CI pipelines."
  homepage "https://github.com/GregoireF/addlicense"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GregoireF/addlicense/releases/download/v0.1.0/addlicense_darwin_amd64.tar.gz"
      sha256 "95685eedaf39dce85aa839bbd66c80145e98f7857aa258a4f5f29a5ab595a3a5"

      define_method(:install) do
        bin.install "addlicense"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GregoireF/addlicense/releases/download/v0.1.0/addlicense_darwin_arm64.tar.gz"
      sha256 "a442e3e12faa1e154b262074f41f25f59d35823fe7e9eda2959739b247eea343"

      define_method(:install) do
        bin.install "addlicense"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GregoireF/addlicense/releases/download/v0.1.0/addlicense_linux_amd64.tar.gz"
      sha256 "44e0405d47d50281e6269b0fd91ac981a626000aedfb0311daf2807200e2cfe3"
      define_method(:install) do
        bin.install "addlicense"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GregoireF/addlicense/releases/download/v0.1.0/addlicense_linux_arm64.tar.gz"
      sha256 "cd566812f0c1fa72dc694e64895c614d63477a4a984be7b314a40eaf0504c5cf"
      define_method(:install) do
        bin.install "addlicense"
      end
    end
  end

  test do
    system "#{bin}/addlicense", "--version"
  end
end
