# This file was generated by GoReleaser. DO NOT EDIT.
cask "addlicense" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "def50e125dd671d0cd94e6c32f7d135d4817bd16b9906bf396d11a5f269a1984"
      url "https://github.com/GregoireF/addlicense/releases/download/v#{version}/addlicense_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "de4640f5bde69bb0cde93abc99ebeebaedf9700dbc1b9636c20ba045c41b0a21"
      url "https://github.com/GregoireF/addlicense/releases/download/v#{version}/addlicense_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "41c2940d65271586fdebe93c2f0a5b77b2c70b07ac49bbc4ac35a20cc6a92e81"
      url "https://github.com/GregoireF/addlicense/releases/download/v#{version}/addlicense_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7035d421fe9a19e942f46630fd7fd28376ec8b62fb083e284e19533ff46d065c"
      url "https://github.com/GregoireF/addlicense/releases/download/v#{version}/addlicense_linux_arm64.tar.gz"
    end
  end

  name "addlicense"
  desc "Fast, minimal license header manager for monorepos and CI pipelines."
  homepage "https://github.com/GregoireF/addlicense"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "addlicense"

  # No zap stanza required

end
