# This file was generated by GoReleaser. DO NOT EDIT.
cask "addlicense" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "2c7374935fb60577be49b75f06ca26a6515a7fc38fb8d8370177917850ca963c"
      url "https://github.com/GregoireF/addlicense/releases/download/v#{version}/addlicense_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2bc9bed1c12561e81510c45b9fea851adbb4841d9bde35ceda875b380063d3c4"
      url "https://github.com/GregoireF/addlicense/releases/download/v#{version}/addlicense_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f21539513b7be7e5cc8f8b2d5551bdf1ab298a0bf11f2d52c7e084534e5035e4"
      url "https://github.com/GregoireF/addlicense/releases/download/v#{version}/addlicense_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f745dd0ea307a6ae8f214e713972edbdd9e209f4b6e9a51c7530125245d8c6a2"
      url "https://github.com/GregoireF/addlicense/releases/download/v#{version}/addlicense_linux_arm64.tar.gz"
    end
  end

  name "addlicense"
  desc "Fast, minimal license header manager for monorepos and CI pipelines."
  homepage "https://github.com/GregoireF/addlicense"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "addlicense"

  # No zap stanza required

end
