# This file was generated by GoReleaser. DO NOT EDIT.
cask "addlicense" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "b5508406f859cb062df2df58c7e7ee52b628c6bd5629ad177aa108caffeb65cf"
      url "https://github.com/GregoireF/addlicense/releases/download/v#{version}/addlicense_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "535b8146e76e0ab86ba898d4dd897ac75eef28f4e19384b3dc3216a2825c256d"
      url "https://github.com/GregoireF/addlicense/releases/download/v#{version}/addlicense_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7dd99d2cd0cac3d39825ee6f1a9c8197d840da1e810adfac8dd5eddb487d95c7"
      url "https://github.com/GregoireF/addlicense/releases/download/v#{version}/addlicense_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "35dbc74089e54783088508bb3a74bb22540419232f78a480ca9a4beaa4d0d54c"
      url "https://github.com/GregoireF/addlicense/releases/download/v#{version}/addlicense_linux_arm64.tar.gz"
    end
  end

  name "addlicense"
  desc "Fast, minimal license header manager for monorepos and CI pipelines."
  homepage "https://github.com/GregoireF/addlicense"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "addlicense"

  # No zap stanza required

end
